### ISSUE TITLE
Add interactive role selection

### ISSUE THREAD

**Issue by davegallant** [theurichde/go-aws-sso#1]
Has there been any consideration to making role selection interactive (i.e. type to filter)?

For example, using a package like https://github.com/AlecAivazis/survey ?

**Comment by theurichde** [comment]
Not yet, no. 

The library itself looks quite nice! 
I will check that out and see if it will fit :)

**Comment by theurichde** [comment]
I just released v0.2.0-alpha.1, it has an interactive account and role selection available.

It uses [promptui](https://github.com/manifoldco/promptui) under the hood, as survey didn't go too well with my terminal

Please try it out and tell me what you think :)

**Comment by davegallant** [comment]
> I just released v0.2.0-alpha.1, it has an interactive account and role selection available.
> 
> It uses [promptui](https://github.com/manifoldco/promptui) under the hood, as survey didn't go too well with my terminal
> 
> Please try it out and tell me what you think :)

Works for me! 🎉

**Comment by theurichde** [comment]
Thanks for your input @davegallant!
 
The changes made it into v0.2.0. 🎈 

Closing this issue for now
