### ISSUE TITLE
[feature] Allow config generation without user prompt

### ISSUE THREAD

**Issue by fishgrimsby** [theurichde/go-aws-sso#104]
**Is your feature request related to a problem? Please describe.**
Currently I don't think it is possible to configure go-aws-sso using the CLI without answering interactive prompts. I would like to be able to generate a config without being prompted for user input. This will let me pre-configure go-aws-sso in a Docker container, for example, without having to copy in a config file as part of the build to work around it

**Describe the solution you'd like**
If `--start-url` or `--region` command options are provided to `go-aws-sso config generate` it should use those values to create the config and not prompt for input. For example: `go-aws-sso config generate --start-url https://my-login.awsapps.com/start --region eu-west-1`

**Describe alternatives you've considered**

**Additional context**
Hopefully the Docker example above provides enough context. If not, I can try to provide more.

**Comment by theurichde** [comment]
Hi @fishgrimsby! Cool, absolutely valid feature request. I will have a look at #105

**Comment by theurichde** [comment]
@fishgrimsby FYI - v1.3.0 is going to be released now :-)

**Comment by fishgrimsby** [comment]
@theurichde That's great! I'll give it a try later 🎉 
Thanks again for the great work
