### ISSUE TITLE
[feature] Support usage as a library?

### ISSUE THREAD

**Issue by eberkund** [theurichde/go-aws-sso#112]
**Description**
I have a small internal Go tool that I use for automating different AWS tasks. But before using that tool I currently have to run the AWS CLI to authenticate. It would be nice if I could bundle this package into my tool as an alternative to installing it separately.

**Describe the solution you'd like**
Maybe some documentation or response here indicating whether supporting this is something you would be interested in or there is anything your foresee as a problem/blocker for this use case.

**Comment by theurichde** [comment]
Hi @eberkund 

Thanks for reaching out! Your request sounds quite similar to #71 

In the pkg folder are some methods for dealing with SSO token and credentials are already exposed. Did you have a look there? 

But I assume you would also like to utilize the account and role prompt?

**Comment by theurichde** [comment]
I am closing this stale issue for now. Please feel free to open it any time again.
