### ISSUE TITLE
Add carriage return after profile definition

### ISSUE THREAD

**Issue by bfanyuk** [theurichde/go-aws-sso#13]
**Is your feature request related to a problem? Please describe.**

1. Execute login command 
2. Try to print the content of credentials file ( cat ~/.aws/credentials )

The last line of the file joins with terminal's current line.
This breaks the terminal. 
I have to manually press Enter to fix the terminal.

**Describe the solution you'd like**
Add newline character in the end of profile definition.

**Describe alternatives you've considered**
cat ~/.aws/credentials _&& echo_

**Additional context**
-

**Comment by theurichde** [comment]
@bfanyuk Works as expected on zsh, but messes up on bash. I will add a new line character
