### ISSUE TITLE
[bug] Doesn't respect the BROWSER environment variable

### ISSUE THREAD

**Issue by XenGi** [theurichde/go-aws-sso#130]
**Describe the bug**

The tool doesn't respect the environment variable `BROWSER` which can be used to temporarily set a different default browser in a shell.

I use this to use a different browser for some tools that require it or to separate work from private projects.

**To Reproduce**
```shell
go-aws-sso
export BROWSER=google-chrome-stable
aws s3 ls
# opens system wide default browser (chromium) instead
```

**Expected behavior**
go-aws-sso should check the content of the `BROWSER` variable and try to use that binary as the browser first. IF that fails it should use `xdg-open` to get the systems default broswer.

**Error Output**
No error just unexpected behaviour.

**Comment by theurichde** [comment]
Hey there 👋🏻 

It's on the To-Do List. 
PRs are also very welcome

**Comment by XenGi** [comment]
No worries. Maybe I'll give it a shot. Haven't found time so far.

**Comment by theurichde** [comment]
I just started working on this

**Comment by theurichde** [comment]
(auto-closed, nice)

@XenGi Please check v1.4.0-beta and tell me if the `BROWSER` env var feature behaves as expected 😄

**Comment by XenGi** [comment]
@theurichde This works perfectly. Thx!
