### ISSUE TITLE
[bug] When 'There is already an authorization flow running' , it only shows error for the `go-aws-sso` command, not the `assume` and `refresh` subcommands

### ISSUE THREAD

**Issue by cfculhane** [theurichde/go-aws-sso#148]
**Describe the bug**
When there is already an authorization flow running, it will print the error as expected when running `go-aws-sso` and exit with code 1:
```
FATAL There is already an authorization flow running
```

However, when running any other commands, it will just just exit with code 1 and no error printed, e.g. `go-aws-sso assume` without args, or  `go-aws-sso refresh`

 
**To Reproduce**
1. Create an auth flow and let it hang in an incomplete state
3. Verify `FATAL There is already an authorization flow running` is returned from `go-aws-sso`
4. Check the `asssume` and `refresh`  subcommands and verify no output is printed

**Expected behavior**
The erro rmessage should print. 

**Error Output**
See above

**Additional context**
If the `--debug` option is meant to print anything for `assume` and `refresh` when in this invalid state, it doesn't do anything either! :(

**Comment by theurichde** [comment]
Hi @cfculhane!

Thanks for reporting. I will take care 🔨

**Comment by theurichde** [comment]
short update: fix is already in progress in my machine, but I am on vacation currently with limited access to my IDE

**Comment by theurichde** [comment]
@cfculhane Both logging issues regarding `assume` and `refresh` are fixed with 1.4.1

Thanks again for reporting 👍🏻
