### ISSUE TITLE
[feature] assume into other account with a role

### ISSUE THREAD

**Issue by kagahd** [theurichde/go-aws-sso#15]
When connected to an AWS account, we'd like to be able to assume into another account with a specific role.
Use case: we, the security team, have an AWS account which we are using to audit other AWS accounts by using a specific role.
Example: 
Log into the Audit account of the security team and copy & paste the env vars into the shell:
```
export AWS_ACCESS_KEY_ID="ASIA3DDUOF..."
export AWS_SECRET_ACCESS_KEY="9SOKzok..."
export AWS_SESSION_TOKEN="IQoJb3Jp..."

```
Connect to the account XYZ to be audited by using the role "AccountSecurityAuditRole":
`go-aws-sso assume -a XYZ -n AccountSecurityAuditRole`

Output: 
```
2022/05/10 10:36:33 AccessToken expired. Start retrieving a new AccessToken.
2022/05/10 10:36:33 Please verify your client request: https://device.sso.eu-central-1.amazonaws.com/?user_code=...
2022/05/10 10:36:33 Still waiting for authorization...
2022/05/10 10:36:36 Still waiting for authorization...
2022/05/10 10:36:39 Something went wrong: ": No access\n\tstatus code: 403, request id: 68d16..."

```
As you can see, it's not possible to assume into the other AWS account.
However, prowler is able to do so:
```
./prowler -A XYZ -R AccountSecurityAuditRole -c check117
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.9.0-13April2022
 |_| the handy cloud security tool

 Date: Mo  9 Mai 2022 18:20:53 CEST
```

**Comment by theurichde** [comment]
Ahoi @kagahd

Assuming into a custom role in an account is somewhat out of scope of go-aws-sso.
I created a small shell script one can use to achieve the same behavior as described in your feature request. 

The script can be found here -> https://gist.github.com/theurichde/23d6b1847afd60b018a517634a8bd677

I'm closing that issue. Thanks!
