### ISSUE TITLE
Extra data error when used as Credential Provider

### ISSUE THREAD

**Issue by joshrivers** [theurichde/go-aws-sso#159]
**First-login error in credential-process mode**
When used as a credential process, `go-aws-sso assume` will cause an error in AWS CLI (and presumably the SDKs) when no session currently exists. This appears to be due to the use of the logger in the output.

**To Reproduce**
1. Assuming ~/.aws/credentials is configured with profiles using `credential_process`
2. `% rm -rf ~/.aws/sso`
3.`% aws sts get-caller-identity`
Output:
```
Extra data: line 1 column 5 (char 4)
```

**Expected behavior**
1. `% rm -rf ~/.aws/sso`
2.`% aws sts get-caller-identity`
Output:
```
{
    "UserId": "....",
    "Account": "...",
    "Arn": "arn:aws:::..."
}
```

**Additional context**
I believe the following lines are related to the error result:
- https://github.com/theurichde/go-aws-sso/blob/main/pkg/sso/aws.go#L127
- https://github.com/theurichde/go-aws-sso/blob/main/pkg/sso/aws.go#L172
- https://github.com/theurichde/go-aws-sso/blob/main/pkg/sso/aws.go#L234

I'd be willing to put together a PR to exclude logging when called with this command, but maybe it should be more nuanced (only when non-interactive? a separate flag? maybe stdout/stderr would resolve the problem with the sdk?)

**Comment by theurichde** [comment]
Hi @joshrivers! Thanks for reporting, good catch 🐛 

I think providing a new flag (e.g. `-q / --quiet`, `--non-interactive`) for the `assume` command will do the trick. 

Either we set the logger output to stderr in [main.go:266](https://github.com/theurichde/go-aws-sso/blob/47b7dc89c0b087e697d9da19c44526d481b41918/cmd/go-aws-sso/main.go#L266) depending on this flag, or discard logs at all.
I tend to discarding the logs, as some people may rely on stdErr and don't want to have arbitrary message in their logs 😅 

I am happy to hear that you would like to implement this fix. Looking forward to it! Please let me know if you need any help!
