### ISSUE TITLE
[feature] generate aws profile config

### ISSUE THREAD

**Issue by automaticgiant** [theurichde/go-aws-sso#174]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

> `aws-sso-util configure populate` takes one or more regions, and generates a profile for each account+role+region combination. The profile names are completely customizable.

**Describe alternatives you've considered**

https://github.com/benkehoe/aws-sso-util?tab=readme-ov-file#configuring-awsconfig is what we are using currently, though for some applications, the dependency chain is a bit hard to manage for non-technical users, though we still wish to facilitate SSO usage though the DefaultCredentialProviderChain

**Comment by theurichde** [comment]
Hi there! 👋🏻 

This feature is out of scope for `go-aws-sso`. 
`go-aws-ssso` is meant to replace this exactly behavior, without the need to populate profiles beforehand.

If you really need to do such thing, you can relatively easy do that yourself with Go, the API go-aws-sso exposes and the [ini library](https://pkg.go.dev/gopkg.in/ini.v1).
