### ISSUE TITLE
Add region override

### ISSUE THREAD

**Issue by davegallant** [theurichde/go-aws-sso#2]
**Is your feature request related to a problem? Please describe.**
It's not possible to override the region without changing the source code.
See https://github.com/theurichde/go-aws-sso/blob/6d35a950f02ba9b193c3ef2c36075669792ee326/main.go#L28

**Describe the solution you'd like**
It'd be nice to be able to specify a region some other way (i.e. flag).

**Describe alternatives you've considered**
N/A

**Additional context**
When using the incorrect region, authorization returns`invalid_grant provided`.

**Comment by theurichde** [comment]
Thanks for reporting!

- [X] Fixed right now with version v0.2.0 


You can either set the region now via e.g. `--region ca-central-1`, `-r ca-central-1` or in the config file via `region: ca-central-1`
