### ISSUE TITLE
[bug] missing config file

### ISSUE THREAD

**Issue by Remownz** [theurichde/go-aws-sso#57]
**Describe the bug**
After using a wrong url on initial setup the config file (go-aws-sso-config.yaml) is missing and following error occurs when running "go-aws-sso":
2022/09/16 08:59:02 Something went wrong: "InvalidRequestException: \n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"578a411b-1c0f-4f6e-9886-937ed711ed6e\"\n  },\n  Error_: \"invalid_request\",\n  Error_description: \"Invalid request\"\n}"

**To Reproduce**
1. use wrong url on initial setup
2. run go-aws-sso

**Expected behavior**
go-aws-sso-config.yaml has been created 

**Edit**
generated filename is "config.yaml" and not "go-aws-sso-config.yaml" as described in readme

**Comment by Remownz** [comment]
"go-aws-sso config generate" helped. So maybe this bug can be closed.

**Comment by theurichde** [comment]
Thanks for reporting this issue! 👍🏼 

I will have a look at the initialization behavior and fix that.

**Comment by theurichde** [comment]
Fixed with #93
