### ISSUE TITLE
[feature] WSL support

### ISSUE THREAD

**Issue by nik-steinebrunner** [theurichde/go-aws-sso#69]
First of all thanks for this awesome tool! 

Since some are using WSL (e.g. Ubuntu) I just wanted to ask if you could make the binary usable here as well.
I think it should be possible to identify the WSL via the file /proc/version by searching for the string "microsoft". 
The command output could then be included in the switch statement as well: https://github.com/theurichde/go-aws-sso/blob/main/internal/aws.go#L155
Then we can use something like that: 
```	
case "wsl":
    err = exec.Command("wslview", url).Start()
````
I look forward to your feedback and am curious to hear what you think about this feature :)

**Comment by theurichde** [comment]
Hi @nik-steinebrunner 

Thanks for your input and your feedback.

Sure, I would be happy to provide the tool also to WSL users. As I don't have WSL running somewhere, I would need your help on that topic. I can implement the feature, but you would have to test it on your side 😅

**Comment by nik-steinebrunner** [comment]
Nice!
Sure, I'm happy to do that. :)

**Comment by theurichde** [comment]
I released [v1.2.0-dev.1](https://github.com/theurichde/go-aws-sso/releases/tag/v1.2.0-dev.1) for testing. 

Tell me how it works for you 😄

**Comment by theurichde** [comment]
@nik-steinebrunner Any news on that side so far?

**Comment by nik-steinebrunner** [comment]
Hi @theurichde 
Sorry, my mistake: I forgot to reply here. I started a review on https://github.com/theurichde/go-aws-sso/pull/70 ;)

**Comment by theurichde** [comment]
Any news on the WSL front here @nik-steinebrunner?

**Comment by theurichde** [comment]
fixed with #70
