### ISSUE TITLE
[bug] WSL not detected correctly, tries to use xdg-open instead of wslview

### ISSUE THREAD

**Issue by fishgrimsby** [theurichde/go-aws-sso#96]
**Describe the bug**
Go-aws-sso does not correctly detect it is running inside WSL. As a result, it does not try to use `wslview` to open the auth request URL, it instead tries to use `xdg-open` which requires the installation of xdg-utils

**To Reproduce**
1. Using WSL once go-aws-sso is configured, attempt to run `go-aws-sso` to authenticate
2. Observe the error output when it attempts to open the URL in browser

**Expected behavior**
go-aws-sso should try to use `wslview` to open the URL

**Error Output**
```
2023-02-16 15:49:38 ERROR exec: "xdg-open": executable file not found in $PATH
github.com/theurichde/go-aws-sso/pkg/sso.openUrlInBrowser
```

**Comment by theurichde** [comment]
Closed with #97 

Thanks for your contribution! 🎈
